GP:
  delta_lengthscale: 0.25
  delta_variance: 0.25
  initial_lengthscale: 6.25
  initial_outputscale: 6.25
  noise: 0.01
  num_fit_samples: 10000
  num_functions: 8
  num_gradient_steps: 50
  num_points: 1024
  sampling_from_GP_lr: 0.05
  threshold_diff: 0.001
  type_of_initial_points: highest
model:
  BB:
    lr_scheduler:
      cooldown: 200
      factor: 0.5
      min_lr: 5.0e-07
      patience: 200
      threshold: 0.0001
    optimizer:
      beta1: 0.9
      lr: 0.001
      optimizer: Adam
      weight_decay: 0.0
    params:
      MLPParams:
        condition_key: SpatialRescaler
        hidden_size: 1024
        image_size: 30
      eta: 0.2
      loss_type: l1
      max_var: 1.0
      mt_type: linear
      num_timesteps: 1000
      objective: grad
      sample_step: 200
      sample_type: linear
      skip_sample: true
  CondStageParams:
    in_channels: 3
    n_stages: 2
    out_channels: 3
  EMA:
    ema_decay: 0.995
    start_ema_step: 4000
    update_ema_interval: 8
    use_ema: true
  latent_before_quant_conv: false
  model_name: BrownianBridge
  model_type: BBDM
  normalize_latent: false
  only_load_latent_mean_std: false
runner: BBDMRunner
task:
  name: TFBind10-Exact-v0
  normalize_x: true
  normalize_y: true
testing:
  alpha: 0.8
  classifier_free_guidance_weight: -1.5
  clip_denoised: false
  num_candidates: 128
  percentile_sampling: 0.2
  type_sampling: highest
training:
  accumulate_grad_batches: 2
  batch_size: 64
  classifier_free_guidance_prob: 0.15
  n_epochs: 100
  no_GP: false
  save_interval: 20
  val_frac: 0.1
  validation_interval: 20
tune: ablation_studies/ab3/grads_50
wandb_name: ab3-tfbind10-grads_50
